### ISSUE TITLE
ChromeAlive Tracker Issue

### ISSUE THREAD

**Issue by blakebyrnes** [ulixee/platform#180]
## ChromeAlive
- [ ] Can't re-launch Datastore Sessions in ChromeAlive
- [ ] Chromealive devtools panel is closed/blank on first load
- [ ] Chromealive hero-script panel and main page hangs when script comes up. 
   - Tracked down to something after we do Page.navigate first time. Could Electron be waiting for something?
- [ ] Timeline is stopping without showing final state of page 
   - stops at last command.. seems like we actually just want to label the stopping point

### Hero Script
- [ ] Hero Script can't see line numbers correctly when inside vm2
- [ ] Source code maps don't work when files are relative
